name: Create Draft Release
on: [workflow_dispatch]
jobs:
  everything:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Install node and NPM
      - uses: actions/setup-node@v4
        with:
          node-version: "19"

      # Install required packages
      - run: npm install
      - run: npm run build

      - name: Reading the system.json for the version
        id: "version"
        run: cat prod.dist/system.json | echo version=`jq -r ".version"` >> "$GITHUB_OUTPUT"

      # Check that tag doesn't exist
      - uses: mukunku/tag-exists-action@v1.5.0
        id: check-tag
        with:
          tag: "v${{ steps.version.outputs.version }}"

      - name: "Ensure that the tag doesn't exist"
        if: ${{ steps.check-tag.outputs.exists == 'true' }}
        run: exit 1

      - name: Move the manifest to a temp file
        id: manifest-move
        run: mv prod.dist/module.json prod.dist/module.temp.json

      - name: Update the download property in the manifest
        id: manifest-update
        run: cat prod.dist/module.temp.json | jq -r --tab '.download = "https://github.com/${{ github.repository }}/releases/download/v${{ steps.version.outputs.version }}/release.zip"' > prod.dist/module.json

      - name: Create the zip
        run: zip -r release.zip prod.dist/*

      - name: Create the draft release
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ steps.version.outputs.version }}"
          commit: ${{ github.ref }}
          draft: true
          generateReleaseNotes: true
          artifacts: "release.zip,prod.dist/module.json"